### ISSUE TITLE
test encoding models

### ISSUE THREAD

**Issue by tehila17-meet** [HuthLab/deep-fMRI-dataset#10]
Hey, 
first of all, thanks for your work!

I was wondering how i can test the trained encoding model on new data? do you have any inference code?

**Comment by alebel14** [comment]
Hello!

Yes we have both code and a test dataset available. In general we use the story wheretheressmoke for the held out test dataset because this story has multiple repeats so you can average across repeats to get a single test set with higher SNR and/or you can use the multiple repeats to calculate a noise ceiling for each voxel. You can see code to do the inference [here](https://github.com/HuthLab/deep-fMRI-dataset/blob/master/encoding/ridge_utils/ridge.py#L66). In general this is done by taking the dot product between the regression model weights and the stimulus matrix for the test set which will result in a timeseries prediction for each voxel for the test story and then you can caculate the correlation between the prediction and held out data. 

We also have some tutorials on this framework using a slightly different codeset (but would still work with this data) [here](https://gallantlab.org/voxelwise_tutorials/_auto_examples/shortclips/03_plot_wordnet_model.html#sphx-glr-auto-examples-shortclips-03-plot-wordnet-model-py) if you are looking for more examples. 

Good luck and feel free to reach out if something is not working as expected!

Amanda
