### ISSUE TITLE
Error when downloading the data?

### ISSUE THREAD

**Issue by csinva** [HuthLab/deep-fMRI-dataset#2]
Hello, thank you for your wonderful work and making this data open-source!

I'm having an issue when trying to download the data, getting the following error:

```bash
git@github.com: Permission denied (publickey).
install(error): data/ds003020 (dataset)
[Failed to clone from all attempted sources: ['git@github.com:OpenNeuroDatasets/ds003020.git']
```

Any idea what the issue could be?

Thanks,
Chandan

**Comment by alebel14** [comment]
Is this happening for all files that are trying to be downloaded or just one? If its all of them I would guess that it is because there is some other AWS public key in your environment. If there is some other AWS keys for other buckets that you use that can cause datalad to fail to download because it gets confused with keys.

**Comment by csinva** [comment]
Gotcha thank you for the very quick response! It was happening for all of them, but was fixed when I just changed the datalad clone argument to this:

`datalad clone https://github.com/OpenNeuroDatasets/ds003020`

**Comment by alebel14** [comment]
Oh thanks for letting me know! I just switched it to this to make it easier for others in the future. I will close this issue. But feel free to reopen if you keep having issues.
